---
apiVersion: hub.traefik.io/v1alpha1
kind: ManagedSubscription
metadata:
  name: customer-subscription
  namespace: traefik-airlines
spec:
  applications:
    - appId: "customers"
  apis:
    - name: flights-api
    - name: tickets-api
  apiPlan:
    name: traefik-airlines-silver-plan
  weight: 10