---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: flights-api
  namespace: traefik-airlines
spec:
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: https://flights.airlines.traefik.EXTERNAL_IP.sslip.io
  cors:
    allowHeadersList:
      - "*"
    allowOriginsList:
      - "*"
    allowMethodsList:
      - "*"
    exposeHeadersList:
      - "*"
    addVaryHeader: true
    allowCredentials: true
    allowOriginListRegex:
      - ".*"
    maxAge: 86400
