---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: employees-api
  namespace: traefik-airlines
spec:
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: http://employees.traefik-airlines.localhost:8080
        - url: http://employees.traefik-airlines.k3d:8080
        - url: http://employees.traefik-airlines.aks
        - url: http://employees.traefik-airlines.eks
        - url: http://employees.traefik-airlines.gke