---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: customers-api
  namespace: traefik-airlines
spec:
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: http://customers.traefik-airlines.localhost:8080
        - url: http://customers.traefik-airlines.k3d:8080
        - url: http://customers.traefik-airlines.aks
        - url: http://customers.traefik-airlines.eks
        - url: http://customers.traefik-airlines.gke