---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: customers-ingress
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`customers.airlines.traefik.EXTERNAL_IP.sslip.io`)
      services:
        - name: customers-app
          port: 3000
  tls:
    certResolver: traefik-airlines
