---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: employees-ingress
  annotations:
    hub.traefik.io/api: employees-api
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`employees.airlines.traefik.EXTERNAL_IP.sslip.io`)
      services:
        - name: employees-app
          port: 3000
      middlewares:
        - name: treblle
  tls:
    certResolver: traefik-airlines
