---
apiVersion: hub.traefik.io/v1alpha1
kind: APICatalogItem
metadata:
  name: traefik-airlines-customers
  namespace: traefik-airlines
spec:
  everyone: true
  apis:
    - name: tickets-api
    - name: flights-api
  apiPlan:
    name: traefik-airlines-bronze-plan