---
apiVersion: hub.traefik.io/v1alpha1
kind: APIPlan
metadata:
  name: traefik-airlines-bronze-plan
  namespace: traefik-airlines
spec:
  title: "Traefik Airlines Bronze Plan"
  description: "Bronze rate limits and quotas"
  rateLimit:
    limit: 1
    period: 10s
  quota:
    limit: 100
    period: 24h
