---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: customers-api
  namespace: traefik-airlines
spec:
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: https://customers.airlines.traefik.EXTERNAL_IP.sslip.io