---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: tickets-api
  namespace: traefik-airlines
spec:
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: https://tickets.airlines.traefik.EXTERNAL_IP.sslip.io