---
apiVersion: hub.traefik.io/v1alpha1
kind: API
metadata:
  name: tickets-api
  namespace: traefik-airlines
spec:
  openApiSpec:
    path: /openapi.yaml
    override:
      servers:
        - url: http://tickets.airlines.traefik.localhost:8080
        - url: http://tickets.airlines.traefik.k3d:8080
        - url: http://tickets.airlines.traefik.aks
        - url: http://tickets.airlines.traefik.eks
        - url: http://tickets.airlines.traefik.gke