apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik-redis
spec:
  releaseName: traefik-redis
  targetNamespace: traefik
  chart:
    spec:
      chart: redis
      version: 19.6.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
  values:
    auth:
      password: topsecretpassword
    replicaCount: 1
