---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: api-ingress-employees
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`employees.traefik-airlines`) || Host(`employees.traefik-airlines.localhost`)
      services:
        - name: employees-app
          port: 3000