---
apiVersion: v1
kind: ConfigMap
metadata:
  name: customers-data
data:
  api.json: |
    {
      "customers": [
        { "id": 1, "firstName": "John", "lastName": "Doe", "points": 100, "status": "bronze" },
        { "id": 2, "firstName": "Jane", "lastName": "Doe", "points": 200, "status": "silver" },
        { "id": 3, "firstName": "John", "lastName": "Smith", "points": 300, "status": "gold" }
      ]
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-app
  template:
    metadata:
      labels:
        app: customers-app
    spec:
      containers:
        - name: api
          image: ghcr.io/traefik-workshops/api-server:v0.1.0
          args: ["-data", "/api/api.json", "-openapi", "/public/openapi.yaml", "-errorrate", "1"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: api-data
            mountPath: /api
          - name: openapi
            mountPath: /public
      volumes:
        - name: api-data
          configMap:
            name: customers-data
        - name: openapi
          configMap:
            name: customers-openapi

---
apiVersion: v1
kind: Service
metadata:
  name: customers-app
  labels:
    app: customers-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: api
  selector:
    app: customers-app
