---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flights-data
data:
  api.json: |
    {
      "flights": [
        { "id": 1, "code": "TL123", "src": "JFK", "dest": "CDG" },
        { "id": 2, "code": "TL234", "src": "CDG", "dest": "JFK" },
        { "id": 3, "code": "TL345", "src": "CDG", "dest": "LYS" }
      ]
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flights-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flights-app
  template:
    metadata:
      labels:
        app: flights-app
    spec:
      containers:
        - name: api
          image: ghcr.io/traefik-workshops/api-server:v0.1.0
          args: ["-data", "/api/api.json", "-openapi", "/public/openapi.yaml", "-errorrate", "1"]
          imagePullPolicy: IfNotPresent
          volumeMounts:
          - name: api-data
            mountPath: /api
          - name: openapi
            mountPath: /public
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      volumes:
        - name: api-data
          configMap:
            name: flights-data
        - name: openapi
          configMap:
            name: flights-openapi

---
apiVersion: v1
kind: Service
metadata:
  name: flights-app
  labels:
    app: flights-app
spec:
  type: ClusterIP
  ports:
    - port: 3000
      name: api
  selector:
    app: flights-app
